// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYrKTIuzJ4CyOxS0EVwvqatg0ncKjwmM',
    appId: '1:602388392410:android:f69533384263a3f1fab8e3',
    messagingSenderId: '602388392410',
    projectId: 'mxcome-1affd',
    storageBucket: 'mxcome-1affd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDwiWagTRGuW63B6rkgME7TzVvrMBeG0',
    appId: '1:602388392410:ios:1597722dbebfa32bfab8e3',
    messagingSenderId: '602388392410',
    projectId: 'mxcome-1affd',
    storageBucket: 'mxcome-1affd.appspot.com',
    androidClientId: '602388392410-1ue9smv2773eqrascun5giahh5g0p4eb.apps.googleusercontent.com',
    iosClientId: '602388392410-v4qk2ldidov7vgevcfjuona4pui4ifg1.apps.googleusercontent.com',
    iosBundleId: 'com.mxcome.app.mxcome',
  );
}
